# Generated by Django 3.2.7 on 2021-09-06 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('email', models.EmailField(max_length=500)),
                ('nick_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(editable=False, max_length=200, unique=True)),
                ('short_intro', models.TextField(default='Hi there🖐', max_length=500)),
                ('profile_image', models.ImageField(default='profiles/user-default.png', upload_to='profiles/')),
                ('social_github', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
                ('solved_count', models.IntegerField(blank=True, default=0, null=True)),
                ('group_id', models.CharField(blank=True, max_length=200, null=True)),
                ('group_reader', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
