# Generated by Django 3.2.7 on 2021-09-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210909_2154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Algorithm',
        ),
    ]
