# Generated by Django 3.2.7 on 2021-09-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_algorithm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='title',
            new_name='name',
        ),
    ]
