# Generated by Django 3.2.7 on 2021-09-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_title_algorithm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coding_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='language',
            field=models.CharField(choices=[('Python3', 'Python3'), ('PyPy3', 'PyPy3'), ('Java11', 'Java11'), ('C99', 'C99'), ('C++17', 'C++17'), ('JS', 'JS'), ('GO', 'GO'), ('Ruby', 'Ruby')], max_length=10),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='type',
            field=models.CharField(choices=[('Implementation', 'Implementation'), ('Greedy', 'Greedy'), ('String', 'String'), ('DataStructures', 'DataStructures'), ('Graphs', 'Graphs'), ('DP', 'DP'), ('Math', 'Math'), ('Bruteforce', 'Bruteforce'), ('etc', 'etc')], max_length=20),
        ),
    ]
