# Generated by Django 3.2.7 on 2021-09-13 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
        ('users', '0016_auto_20210913_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_groups.studygroup'),
        ),
    ]
