# Generated by Django 3.2.7 on 2021-09-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='group_leader',
            new_name='is_leader',
        ),
    ]
