# Generated by Django 3.2.7 on 2021-09-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_group_leader_profile_is_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='short_intro',
            field=models.TextField(default='Hi there', max_length=500),
        ),
    ]
