# Generated by Django 3.2.7 on 2021-09-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profile_short_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, default='네카라쿠배', max_length=500, null=True),
        ),
    ]
