# Generated by Django 3.2.7 on 2021-09-13 04:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('group_image', models.ImageField(blank=True, default='study_groups/default.jpg', null=True, upload_to='study_groups/')),
                ('goal', models.CharField(blank=True, max_length=500, null=True)),
                ('penalty', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
