# Generated by Django 3.2.7 on 2021-09-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0002_alter_studygroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='group_image',
            field=models.ImageField(blank=True, default='study_groups/Cloud.png', null=True, upload_to='study_groups/'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
